AllCops:
  Exclude:
    - 'bin/**/*'
    - 'db/**/*'
    - 'Gemfile'
  TargetRubyVersion: 2.3

Rails:
  Enabled: true

Rails/OutputSafety:
  Enabled: false

HasAndBelongsToMany:
  Enabled: false

Metrics/LineLength:
  Max: 120

Documentation:
  Enabled: false

ClassAndModuleChildren:
  Enabled: false

FrozenStringLiteralComment:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/MethodLength:
  Max: 20

Metrics/BlockLength:
  Enabled: false

Style/CaseEquality:
  Enabled: false

Style/SignalException:
  Enabled: false

Lint/UnreachableCode:
  Enabled: false
